### ISSUE TITLE
modify should catch the ModifyJsError and return an empty row

### ISSUE THREAD

**Issue by Downchuck** [williamkapke/mongo-mock#107]
Currently if there is a filter on findOneAndUpdate and returning a document there is no matching row the modify function does not catch an error for asyncish.

`ModifyJsError: cannot use the part 'colName' to traverse undefined`

This should have instead returned an empty row for the update.

**Comment by TanukiSharp** [comment]
I ran into this issue and found out the problem. It is fixable from `mongo-mock`, whereas indeed `modifyjs` could be more resilient.

At line https://github.com/williamkapke/mongo-mock/blob/master/lib/collection.js#L447, when there is no documents matched (`docs` is an empty array), the expression `!docs.length` is `true`, but if `options.upsert` is set to `false`, then it goes to the else, here:
https://github.com/williamkapke/mongo-mock/blob/master/lib/collection.js#L466
Two lines later, the statement `var conflict = modify(docs[0], data, state);` passes `undefined` to the modify function because the `docs` array is empty.

Then it goes to `modifyjs` where things go wrong.

The fix is to replace `else {` by `else if (docs.length > 0) {` at at line 466 of collection.js (https://github.com/williamkapke/mongo-mock/blob/master/lib/collection.js#L466)

This is an easy fix, and it doesn't break any uni tests.

Let me know if you do it (@Downchuck or @williamkapke) of if you want me to do it.

Thanks.
