### ISSUE TITLE
support for $unset

### ISSUE THREAD

**Issue by benjamine** [williamkapke/mongo-mock#45]
I noticed `$unset` operator is not supported, making it impossible to delete keys from an object.
it should be pretty straightforward to add around:

https://github.com/williamkapke/mongo-mock/blob/648f55e9f89ab23509f3376bf2f5ff68495b4492/lib/collection.js#L483

perhaps this repo could rely on a lib like https://www.npmjs.com/package/modifyjs for doing each `updateOne`, getting a lot of mongo update operators supported.

**Comment by williamkapke** [comment]
This seems like a pretty good suggestion! Although, I'd remove the existing commands we have if they're in modifyjs.

It supports:
- $min
- $max
- $inc
- $set / $setOnInsert
- $unset
- $push + $each, $slice, $sort, $position
- $pushAll
- $addToSet
- $pop
- $pullAll
- $rename

We have:
- $set / $setOnInsert
- $inc
- $addToSet
- $push + $each $slice


Seems like there is just 1 problem: It doesn't have an open source License!
<sup>It says it is based on Meteor's code which is MIT but attribution is not otherwise given to that project.</sup>

ping @lgandecki

**Comment by lgandecki** [comment]
Hey, good catch - added the license!
Interesting project - could you tell a bit more why have you decided to build this, instead of rely on something like tingodb? I personally use in-memory mongo replacements a lot - mainly for testing.. I admit - there ARE some disadvantages of using tingodb - so I might actually want to contribute to this at some point, but would love to hear your reasons :)

Let me guy know if I can do anything to help you integrate modifyjs.

**Comment by lgandecki** [comment]
btw, this is exactly how rxdb is using modifyjs, to keep this concern out of it's codebase:
https://github.com/pubkey/rxdb/blob/master/src/plugins/update.js#L3

**Comment by benjamine** [comment]
amazing! thanks @lgandecki

**Comment by williamkapke** [comment]
Excellent @lgandecki! Thanks for adding it. Don't forget to update your [package.json](https://github.com/lgandecki/modifyjs/blob/master/package.json#L23)!

To answer your questions: I started this project when I was working for Tinder. We needed something super lightweight with little/no dependencies. It was used while running tests & some devs wanted to be able to work offline/airplane mode. Specifically for our tests, we needed for it to work `asyncish`- meaning the calls/commands needed to break from the original executing context and return the response at a somewhat random time. It does not strive to be a full fledge database that should be used in a production product.

`tingodb` has some dynamically built javascript strings... which makes security auditors nervous even if they're technically benign. No real other reason. It seems like a fine module.

**Comment by williamkapke** [comment]
I have integrated modifyjs 🎉 

I felt this was semver major worthy so v3.0.0 has been published.

**Comment by benjamine** [comment]
oh that's amazing!! thank you both! 🎆

**Comment by lgandecki** [comment]
Very cool! :) 
I realize that I have discrepant licenses now in package.json and LICENSE.md.. not sure if updating the package.json is worth the noise on npm (bumping a version) and github? Those licenses are pretty much compatible anyway

As for the asyncishness - I get it. Makes sense. I actually recently stumbled upon a problem where my integration tests (using tingodb) passed by e2e (with real mongo) failed - because of that. I will have to take a closer look at this project soon, I imagine the transition should be rather smooth. 

Do you somehow track the remaining things that have to be done to be able to have 1:1 with mongo?

**Comment by yaplas** [comment]
Hi !!,
Im trying the updateOne with the `$set` and seems like it is doing a "deep merge" but real mongo db does a "shallow merge".
<img width="669" alt="2018-04-10_1210" src="https://user-images.githubusercontent.com/2750777/38565861-c307eca0-3cb8-11e8-81b9-31e1fd063877.png">

the result shoud be just: `{value: {c: 2}}`

**Comment by lgandecki** [comment]
@yaplas interesting! it would be fantastic if you could create a PR with a failing test here https://github.com/lgandecki/modifyjs

**Comment by yaplas** [comment]
@lgandecki seems the issue is not in modifyjs is in the mongo-mock code, because they are doing a lodash merge after calling modifyjs

**Comment by wjagodfrey** [comment]
This is still not working in the latest version
```
await db.collection(mongoCollections.ENTITY_OWNERSHIP)
    .update(
        query,
        {
          $unset: {
            'fields.zip': ''
          }
        }
      );
```
This request does nothing, though it works well against `Mongo@3.6.4`

```
$ npm ls modifyjs
└─┬ mongo-mock@3.1.0
  └── modifyjs@0.3.1
```

**Comment by wjagodfrey** [comment]
I thought this may have been to do with a defective test on `modofyjs`, but I've fixed the test locally and it works.
https://github.com/lgandecki/modifyjs/pull/2

**Comment by lgandecki** [comment]
Yeah, as @yaplas demonstrated above it looks like it works properly on modifyjs side. What an unusual coincidence that the test for that particular operation was incorrect itself! :) Thanks for catching and for the PR.

**Comment by wjagodfrey** [comment]
The issue occurs only for deep values. It's caused by these lines
https://github.com/williamkapke/mongo-mock/blob/master/lib/collection.js#L433-L435

I've opened a PR here: https://github.com/williamkapke/mongo-mock/pull/58

**Comment by williamkapke** [comment]
yeah- nothing wrong with `modifyjs`. This lib needs to mutate the objects in the underlying collections- but `modifyjs` only returns copies (per the intended design). Maybe @lgandecki will find a need to have a mutate feature someday ;)

`$unset` is working with dot notation now. Thanks everyone!
